# Generated by Django 4.2.13 on 2024-06-10 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("docent", "0002_usersession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chatting",
        ),
    ]
