# Generated by Django 4.2.13 on 2024-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docent", "0003_delete_chatting"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("question", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
