# Generated by Django 4.2.13 on 2024-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docent", "0004_inputdata_delete_usersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputdata",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
