# Generated by Django 4.2.13 on 2024-06-11 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("docent", "0005_alter_inputdata_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inputdata",
            old_name="image",
            new_name="file",
        ),
    ]
